# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Fabric
minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2

# Mod
mod_version=9.0.4+fabric.1
maven_group=com.blakebr0.mysticalagriculture
archives_base_name=MysticalAgriculture-Fabric

# Dependencies
cucumber_version=26.2-9.0.5+fabric.1
energy_version=5.0.0
jei_version=30.14.0.90
jade_version=8347273
